#[[
  File: cmake/pipeline/lint/lint-cpp.cmake
  Brief: C++ lint using clang-tidy, plus OneTestPerFile plugin enforcement for tests.
]]

include_guard(GLOBAL)

function(lint_cpp)
  # clang-tidy over project sources
  set(_DO_CPP TRUE)
  if(LINT_CHANGED_ONLY)
    _git_changed_files(_CPP_CHANGED "*.cpp")
    if(NOT _CPP_CHANGED)
      message(STATUS "C++: no changed sources; skipping")
      set(_DO_CPP FALSE)
    endif()
  endif()
  # Ensure we have a compile DB root for both clang-tidy and OTPF include paths
  if(NOT DEFINED _BIN_DIR)
    if(DEFINED LINT_BUILD_DIR)
      set(_BIN_DIR "${LINT_BUILD_DIR}")
    else()
      set(_BIN_DIR "${CMAKE_SOURCE_DIR}/build/llvm-debug")
    endif()
    if(NOT EXISTS "${_BIN_DIR}/compile_commands.json")
      set(_ALT_DIR "${CMAKE_SOURCE_DIR}/build/arm64-debug")
      if(EXISTS "${_ALT_DIR}/compile_commands.json")
        set(_BIN_DIR "${_ALT_DIR}")
      else()
        file(GLOB CC_JSON_FILES "${CMAKE_SOURCE_DIR}/build/*/compile_commands.json")
        list(LENGTH CC_JSON_FILES _CC_LEN)
        if(_CC_LEN GREATER 0)
          list(GET CC_JSON_FILES 0 _CC_PATH)
          get_filename_component(_BIN_DIR "${_CC_PATH}" DIRECTORY)
        endif()
      endif()
    endif()
  endif()

  if(_DO_CPP)
    find_program(CLANG_TIDY_EXE clang-tidy)
    if(NOT CLANG_TIDY_EXE)
      message(FATAL_ERROR "clang-tidy is required. Run 'make ready/fix' to install llvm.")
    endif()

    # Validate compile_commands.json for clang-tidy execution
    if(NOT EXISTS "${_BIN_DIR}/compile_commands.json")
      message(FATAL_ERROR "clang-tidy compile database missing. Run 'make configure' first.")
    endif()

    include("${CMAKE_SOURCE_DIR}/cmake/pipeline/sdk.cmake")
    crsce_sdk_env_prefix(_ENV_PREFIX)
    if(_ENV_PREFIX)
      set(_ENV_PREFIX "${_ENV_PREFIX} ")
    endif()
    crsce_sdk_tidy_extra_args(_EXTRA_ARGS_LIST)
    set(_EXTRA_ARGS "")
    if(_EXTRA_ARGS_LIST)
      set(_EXTRA_ARGS ${_EXTRA_ARGS_LIST})
    endif()
    set(_RES_DIR "")
    execute_process(COMMAND /opt/homebrew/opt/llvm/bin/clang++ -print-resource-dir OUTPUT_VARIABLE _RES_DIR OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _rd_rc)
    if(_rd_rc EQUAL 0 AND _RES_DIR)
      list(APPEND _EXTRA_ARGS "-extra-arg=-resource-dir=${_RES_DIR}")
    endif()
    if(NOT EXISTS "${_BIN_DIR}/compile_commands.json")
      message(FATAL_ERROR "clang-tidy compile database missing at '${_BIN_DIR}'.")
    endif()
    set(_HDR_FILTER "^(include|src|cmd|test)/")
    set(_BASE_CMD ${CLANG_TIDY_EXE} -p ${_BIN_DIR} -warnings-as-errors=* "-header-filter=${_HDR_FILTER}")

    # Gather C++ files
    if(LINT_CHANGED_ONLY)
      set(_SRC_LIST ${_CPP_CHANGED})
    else()
      execute_process(COMMAND bash -lc "git ls-files '*.cpp'" OUTPUT_VARIABLE _SRC_LIST_STR OUTPUT_STRIP_TRAILING_WHITESPACE)
      separate_arguments(_SRC_LIST UNIX_COMMAND "${_SRC_LIST_STR}")
    endif()
    if(NOT _SRC_LIST)
      set(_SRC_LIST)
    endif()
    # Exclude C++ sources under tools/** from main clang-tidy pass; they have separate checks
    list(FILTER _SRC_LIST EXCLUDE REGEX "^tools/.*\\.cpp$")

    # Run clang-tidy
    if(LINT_PARALLEL)
      string(JOIN " " _EXTRA_STR ${_EXTRA_ARGS})
      set(_BASE_STR "${CLANG_TIDY_EXE} -p ${_BIN_DIR} -warnings-as-errors=* -header-filter='^(include|src|cmd|test)/' ${_EXTRA_STR}")
      # Write newline-separated file list and feed to xargs for parallel runs
      string(JOIN "\n" _SRC_NL ${_SRC_LIST})
      set(_LIST_FILE "${_BIN_DIR}/.clang_tidy_files.txt")
      file(WRITE "${_LIST_FILE}" "${_SRC_NL}\n")
      _run("clang-tidy (parallel)" bash -lc "cat '${_LIST_FILE}' | xargs -P ${_NPROC} -n 1 ${_BASE_STR}")
    else()
      foreach(_FILE IN LISTS _SRC_LIST)
        if(IS_ABSOLUTE "${_FILE}")
          set(_ABS_FILE "${_FILE}")
        else()
          get_filename_component(_ABS_FILE "${CMAKE_SOURCE_DIR}/${_FILE}" ABSOLUTE)
        endif()
        if(APPLE AND DEFINED CRSCE_MACOS_SDK)
          execute_process(COMMAND ${CMAKE_COMMAND} -E env SDKROOT=${CRSCE_MACOS_SDK} ${_BASE_CMD} ${_EXTRA_ARGS} ${_ABS_FILE} RESULT_VARIABLE _one_rc)
        else()
          execute_process(COMMAND ${_BASE_CMD} ${_EXTRA_ARGS} ${_ABS_FILE} RESULT_VARIABLE _one_rc)
        endif()
        if(NOT _one_rc EQUAL 0)
          message(STATUS "-- Linter failed --")
          message(FATAL_ERROR "clang-tidy failed on ${_FILE} (${_one_rc}).")
        endif()
      endforeach()
    endif()
  endif()

  # OneTestPerFile enforcement across test/**/*.cpp (ENABLED by default)
  # Build/locate plugin
  set(_PLUG_LIB)
  file(GLOB _OTPF_DYLIB "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.dylib")
  file(GLOB _OTPF_SO    "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.so")
  file(GLOB _OTPF_DLL   "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.dll")
  if(_OTPF_DYLIB)
    list(GET _OTPF_DYLIB 0 _PLUG_LIB)
  elseif(_OTPF_SO)
    list(GET _OTPF_SO 0 _PLUG_LIB)
  elseif(_OTPF_DLL)
    list(GET _OTPF_DLL 0 _PLUG_LIB)
  endif()
  if(NOT _PLUG_LIB)
    message(STATUS "Building OneTestPerFile plugin (missing lib)...")
    execute_process(
      COMMAND ${CMAKE_COMMAND} -D SOURCE_DIR=${CMAKE_SOURCE_DIR} -D BUILD_DIR=${CMAKE_SOURCE_DIR}/build -D ONLY_GROUP=clang-plugins/OneTestPerFile -P ${CMAKE_SOURCE_DIR}/cmake/pipeline/deps.cmake
      RESULT_VARIABLE _DEP_RC)
    if(NOT _DEP_RC EQUAL 0)
      message(FATAL_ERROR "Failed to build OneTestPerFile plugin (${_DEP_RC}).")
    endif()
    file(GLOB _OTPF_DYLIB2 "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.dylib")
    file(GLOB _OTPF_SO2    "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.so")
    file(GLOB _OTPF_DLL2   "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneTestPerFile/*OneTestPerFile*.dll")
    if(_OTPF_DYLIB2)
      list(GET _OTPF_DYLIB2 0 _PLUG_LIB)
    elseif(_OTPF_SO2)
      list(GET _OTPF_SO2 0 _PLUG_LIB)
    elseif(_OTPF_DLL2)
      list(GET _OTPF_DLL2 0 _PLUG_LIB)
    endif()
  endif()
  if(NOT _PLUG_LIB)
    message(FATAL_ERROR "OneTestPerFile plugin library not found after build.")
  endif()

  # Resolve clang++
  # Prefer Homebrew clang++ for plugin support
  if(EXISTS "/opt/homebrew/opt/llvm/bin/clang++")
    set(OTPF_CLANGXX_EXE "/opt/homebrew/opt/llvm/bin/clang++")
  else()
    find_program(OTPF_CLANGXX_EXE clang++)
    if(NOT OTPF_CLANGXX_EXE)
      set(OTPF_CLANGXX_EXE clang++)
    endif()
  endif()

  # Compose base args
  set(_BASE)
  list(APPEND _BASE -fsyntax-only -std=c++23)
  list(APPEND _BASE -I${CMAKE_SOURCE_DIR}/include)
  list(APPEND _BASE -I${CMAKE_SOURCE_DIR}/src)
  list(APPEND _BASE -I${CMAKE_SOURCE_DIR}/src/common)
  list(APPEND _BASE -I${CMAKE_SOURCE_DIR}/src/Compress)
  list(APPEND _BASE -I${CMAKE_SOURCE_DIR}/src/Decompress)
  list(APPEND _BASE -I${_BIN_DIR}/_deps/googletest-src/googletest/include)
  list(APPEND _BASE -I${_BIN_DIR}/_deps/googletest-src/googletest)
  # Ensure resource dir if discoverable
  execute_process(COMMAND ${OTPF_CLANGXX_EXE} -print-resource-dir OUTPUT_VARIABLE _RES_DIR2 OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _rd2)
  if(_rd2 EQUAL 0 AND _RES_DIR2)
    list(APPEND _BASE -resource-dir=${_RES_DIR2})
  endif()
  string(JOIN " " _BASE_STR ${_BASE})

  # Gather test sources (all)
  execute_process(COMMAND bash -lc "git ls-files 'test/**/*.cpp'"
                  OUTPUT_VARIABLE _TEST_LIST
                  OUTPUT_STRIP_TRAILING_WHITESPACE)
  separate_arguments(_TEST_SRCS UNIX_COMMAND "${_TEST_LIST}")
  foreach(_T IN LISTS _TEST_SRCS)
    if(NOT IS_ABSOLUTE "${_T}")
      set(_TF "${CMAKE_SOURCE_DIR}/${_T}")
    else()
      set(_TF "${_T}")
    endif()
    if(EXISTS "${_TF}")
      # Skip non-GTest CLI helpers and plugin fixtures (intentional violations)
      if(_TF MATCHES "/test/cmd/hasher/helpers/.*\\.cpp$")
        continue()
      endif()
      if(_TF MATCHES "/test/tools/clang-plugins/.*/fixtures/.*\\.cpp$")
        continue()
      endif()
      set(_CMD "${OTPF_CLANGXX_EXE} ${_BASE_STR} -Xclang -load -Xclang \"${_PLUG_LIB}\" -Xclang -plugin -Xclang one-test-per-file \"${_TF}\"")
      # Run OTPF; non-zero exit is a failure.
      execute_process(COMMAND bash -lc "${_CMD}"
                      OUTPUT_VARIABLE _OTPF_OUT
                      ERROR_VARIABLE _OTPF_ERR
                      RESULT_VARIABLE _OTPF_RC)
      if(NOT _OTPF_RC EQUAL 0)
        if(NOT _OTPF_OUT AND NOT _OTPF_ERR)
          message(STATUS "  😬 🤷 😬 Lint passed for ${_T}")
        else()
          message(STATUS "-- 🔥Linter failed 🔥 --")
          message(FATAL_ERROR "  🔥OTPF failed on ${_T} (${_OTPF_RC}).\n${_OTPF_OUT}${_OTPF_ERR}")
        endif()
      else()
        message(STATUS "  ✅ Lint passed for ${_T}")
      endif()
    endif()
  endforeach()

  # OneDefinitionPerCppFile enforcement across src/**/*.cpp
  # Build/locate plugin
  set(_ODPCPP_LIB)
  file(GLOB _ODPCPP_DYLIB "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.dylib")
  file(GLOB _ODPCPP_SO    "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.so")
  file(GLOB _ODPCPP_DLL   "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.dll")
  if(_ODPCPP_DYLIB)
    list(GET _ODPCPP_DYLIB 0 _ODPCPP_LIB)
  elseif(_ODPCPP_SO)
    list(GET _ODPCPP_SO 0 _ODPCPP_LIB)
  elseif(_ODPCPP_DLL)
    list(GET _ODPCPP_DLL 0 _ODPCPP_LIB)
  endif()
  if(NOT _ODPCPP_LIB)
    message(STATUS "Building OneDefinitionPerCppFile plugin (missing lib)...")
    execute_process(
      COMMAND ${CMAKE_COMMAND} -D SOURCE_DIR=${CMAKE_SOURCE_DIR} -D BUILD_DIR=${CMAKE_SOURCE_DIR}/build -D ONLY_GROUP=clang-plugins/OneDefinitionPerCppFile -P ${CMAKE_SOURCE_DIR}/cmake/pipeline/deps.cmake
      RESULT_VARIABLE _DEP_RC2)
    if(NOT _DEP_RC2 EQUAL 0)
      message(FATAL_ERROR "Failed to build OneDefinitionPerCppFile plugin (${_DEP_RC2}).")
    endif()
    file(GLOB _ODPCPP_DYLIB2 "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.dylib")
    file(GLOB _ODPCPP_SO2    "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.so")
    file(GLOB _ODPCPP_DLL2   "${CMAKE_SOURCE_DIR}/build/tools/clang-plugins/OneDefinitionPerCppFile/*OneDefinitionPerCppFile*.dll")
    if(_ODPCPP_DYLIB2)
      list(GET _ODPCPP_DYLIB2 0 _ODPCPP_LIB)
    elseif(_ODPCPP_SO2)
      list(GET _ODPCPP_SO2 0 _ODPCPP_LIB)
    elseif(_ODPCPP_DLL2)
      list(GET _ODPCPP_DLL2 0 _ODPCPP_LIB)
    endif()
  endif()
  if(NOT _ODPCPP_LIB)
    message(FATAL_ERROR "OneDefinitionPerCppFile plugin library not found after build.")
  endif()

  # Gather src C++ sources
  execute_process(COMMAND bash -lc "git ls-files 'src/**/*.cpp'"
                  OUTPUT_VARIABLE _SRC_CPPS
                  OUTPUT_STRIP_TRAILING_WHITESPACE)
  separate_arguments(_SRC_CPPS_LIST UNIX_COMMAND "${_SRC_CPPS}")
  foreach(_S IN LISTS _SRC_CPPS_LIST)
    if(NOT IS_ABSOLUTE "${_S}")
      set(_SF "${CMAKE_SOURCE_DIR}/${_S}")
    else()
      set(_SF "${_S}")
    endif()
    if(EXISTS "${_SF}")
      set(_CMD2 "${OTPF_CLANGXX_EXE} ${_BASE_STR} -Xclang -load -Xclang \"${_ODPCPP_LIB}\" -Xclang -plugin -Xclang one-definition-per-cpp-file \"${_SF}\"")
      execute_process(COMMAND bash -lc "${_CMD2}"
                      OUTPUT_VARIABLE _ODPCPP_OUT
                      ERROR_VARIABLE _ODPCPP_ERR
                      RESULT_VARIABLE _ODPCPP_RC)
      if(NOT _ODPCPP_RC EQUAL 0)
        if(NOT _ODPCPP_OUT AND NOT _ODPCPP_ERR)
          message(STATUS "  😬 🤷 😬 Lint passed for ${_S}")
        else()
          message(STATUS "-- 🔥Linter failed 🔥 --")
          message(FATAL_ERROR "  🔥ODPCPP failed on ${_S} (${_ODPCPP_RC}).\n${_ODPCPP_OUT}${_ODPCPP_ERR}")
        endif()
      else()
        message(STATUS "  ✅ Lint passed for ${_S}")
      endif()
    endif()
  endforeach()
endfunction()
