/**
 * @file LtpTable.h
 * @copyright (c) 2026 Sam Caldwell. See LICENSE.txt.
 * @brief Non-linear lookup-table partitions LTP1–LTP4 for B.20.
 *
 * Four pseudorandom partitions of all s^2 = 261,121 cells into 511 lines of
 * exactly 511 cells each. Generated by Fisher-Yates shuffle with deterministic
 * LCG seeds. Forward table: cell → flat stat index. Reverse table: line → cells.
 */
#pragma once

#include <array>
#include <cstdint>

namespace crsce::decompress::solvers {

    /**
     * @name kLtpS
     * @brief Matrix dimension (511).
     */
    inline constexpr std::uint16_t kLtpS = 511;

    /**
     * @name kLtpNumLines
     * @brief Lines per LTP partition (511).
     */
    inline constexpr std::uint16_t kLtpNumLines = 511;

    /**
     * @name kLtp1Base
     * @brief Flat stat-array base for LTP1 lines (= kBasicLines = 6s-2 = 3064).
     */
    inline constexpr std::uint32_t kLtp1Base = 3064;

    /**
     * @name kLtp2Base
     * @brief Flat stat-array base for LTP2 lines (7s-2 = 3575).
     */
    inline constexpr std::uint32_t kLtp2Base = 3575;

    /**
     * @name kLtp3Base
     * @brief Flat stat-array base for LTP3 lines (8s-2 = 4086).
     */
    inline constexpr std::uint32_t kLtp3Base = 4086;

    /**
     * @name kLtp4Base
     * @brief Flat stat-array base for LTP4 lines (9s-2 = 4597).
     */
    inline constexpr std::uint32_t kLtp4Base = 4597;

    /**
     * @struct LtpCell
     * @name LtpCell
     * @brief A (row, column) cell coordinate pair used in LTP reverse tables.
     */
    // NOLINTBEGIN(misc-non-private-member-variables-in-classes)
    struct LtpCell {
        /**
         * @name r
         * @brief Row index.
         */
        std::uint16_t r;

        /**
         * @name c
         * @brief Column index.
         */
        std::uint16_t c;
    };
    // NOLINTEND(misc-non-private-member-variables-in-classes)

    /**
     * @name ltpFlatIndices
     * @brief Return precomputed flat stat indices for LTP1–LTP4 at cell (r, c).
     *
     * Returns {kLtp1Base + ltp1_line(r,c), kLtp2Base + ltp2_line(r,c),
     *          kLtp3Base + ltp3_line(r,c), kLtp4Base + ltp4_line(r,c)}.
     * Table is a function-local static, initialized on first call via Fisher-Yates.
     *
     * @param r Row index in [0, kLtpS).
     * @param c Column index in [0, kLtpS).
     * @return Reference to array of 4 flat stat indices [LTP1, LTP2, LTP3, LTP4].
     */
    [[nodiscard]] const std::array<std::uint16_t, 4> &ltpFlatIndices(std::uint16_t r, std::uint16_t c);

    /**
     * @name ltp1CellsForLine
     * @brief Return the 511 cells on LTP1 line k.
     * @param k Line index in [0, kLtpNumLines).
     * @return Reference to array of 511 LtpCell entries.
     */
    [[nodiscard]] const std::array<LtpCell, 511> &ltp1CellsForLine(std::uint16_t k);

    /**
     * @name ltp2CellsForLine
     * @brief Return the 511 cells on LTP2 line k.
     * @param k Line index in [0, kLtpNumLines).
     * @return Reference to array of 511 LtpCell entries.
     */
    [[nodiscard]] const std::array<LtpCell, 511> &ltp2CellsForLine(std::uint16_t k);

    /**
     * @name ltp3CellsForLine
     * @brief Return the 511 cells on LTP3 line k.
     * @param k Line index in [0, kLtpNumLines).
     * @return Reference to array of 511 LtpCell entries.
     */
    [[nodiscard]] const std::array<LtpCell, 511> &ltp3CellsForLine(std::uint16_t k);

    /**
     * @name ltp4CellsForLine
     * @brief Return the 511 cells on LTP4 line k.
     * @param k Line index in [0, kLtpNumLines).
     * @return Reference to array of 511 LtpCell entries.
     */
    [[nodiscard]] const std::array<LtpCell, 511> &ltp4CellsForLine(std::uint16_t k);

} // namespace crsce::decompress::solvers
